### ISSUE TITLE
How to add metadata column in onboarding file for bronze table

### ISSUE THREAD

**Issue by UlrichMelende** [databrickslabs/dlt-meta#100]
Hello,

I want to load data from csv file to bronze table using dlt-meta.
My question : is it possible to add metadata column which is not in the csv source file by adding it in onboarding file? If yes, how to do it.

**Comment by ravi-databricks** [comment]
There are two ways:
1. use file metadata as shown [here](https://github.com/databrickslabs/dlt-meta/blob/95867fd4d012c49db637a8759014fb603dff51f1/examples/onboarding.template#L11), refer to [docs](https://databrickslabs.github.io/dlt-meta/getting_started/metadatapreperation/#onboardingjson-file-structure-examples-autoloaderhttpsgithubcomdatabrickslabsdlt-metablobmainexamplescloudfiles-onboardingtemplate-eventhubhttpsgithubcomdatabrickslabsdlt-metablobmainexampleseventhub-onboardingtemplate-kafkahttpsgithubcomdatabrickslabsdlt-metablobmainexampleskafka-onboardingtemplate-)

For cloudFiles option _metadata columns addtiion there is **source_metadata** tag with attributes: **include_autoloader_metadata_column** flag (True or False value) will add **_metadata** column to target bronze dataframe, **autoloader_metadata_col_name** if this provided then will be used to rename **_metadata** to this value otherwise default is **source_metadata,select_metadata_cols:{key:value}** will be used to extract columns from **_metadata. key** is target dataframe column name and value is expression used to add column from **_metadata** column

2. Use custom transformations shown [here](https://github.com/databrickslabs/dlt-meta/blob/main/examples/dlt_meta_pipeline_custom_transform.ipynb)

**Comment by UlrichMelende** [comment]
Thank you, option2 works very well.
